DROP DATABASE IF EXISTS registration;
CREATE DATABASE IF NOT EXISTS registration;
USE registration;
CREATE TABLE accounts(
  id INT AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  email VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(254) NOT NULL,
  datecreated DATETIME
    DEFAULT CURRENT_TIMESTAMP,
  dateupdated TIMESTAMP
    DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP
);